st_admin:
    resource: "@STAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

st_auth:
    resource: "@STUserBundle/Resources/config/routing.yml"
    prefix:   /login

elfinder:
    resource: "@FMElfinderBundle/Resources/config/routing.yml"
st_figure:
    resource: "@STFigureBundle/Resources/config/routing.yml"
    prefix:   /