# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    figure_service:
        class: ST\FigureBundle\Models\Service\FigureService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    layout_service:
        class: ST\FigureBundle\Models\Service\LayoutService
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
