services:
    figure_service:
        class: ST\FigureBundle\Models\Service\FigureService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    layout_service:
        class: ST\FigureBundle\Models\Service\LayoutService
