services:
    figure_service:
        class: ST\FigureBundle\Models\Service\FigureService
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
    layout_service:
        class: ST\FigureBundle\Models\Service\LayoutService
    ST_figure.event_listener.figure_entity:
        class: ST\FigureBundle\EventListener\FigureEntityListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postFlush }
