<?php

namespace ST\FigureBundle\Repository;

/**
 * FigureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FigureHistoRepository extends \Doctrine\ORM\EntityRepository
{
}
